# Generated by Django 3.2.3 on 2021-06-03 19:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_org_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='About',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('GHA', 'GHA'), ('GSA', 'GSA'), ('Airline', 'Airline')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos', verbose_name='Company logo'),
        ),
    ]
